set_property IOSTANDARD LVCMOS33 [get_ports {cout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputW[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputW[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputW[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inputW[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {s[0]}]

set_property PACKAGE_PIN AB15 [get_ports {cout[3]}]
